[package]
name = "lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "*"
lambda_runtime = "*"
serde = { version = "*", features = ["derive"] }
tokio = { version = "*", features = ["macros"] }
url = "*"
serde_json = "*"
anyhow = "*"
querystring = "*"