[package]
name = "lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "*"
lambda_runtime = "*"
serde = { version = "*", features = ["derive"] }
tokio = { version = "*", features = ["full"] }
url = "*"
serde_json = "*"
anyhow = "*"
ureq = { version = "*", features = ["socks-proxy", "charset", "json"] }
headers = "*"
chrono = "*"